# Generated by Django 4.2.4 on 2023-10-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
