# Generated by Django 4.2.5 on 2023-10-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_auto_20231024_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.IntegerField()),
                ('recommended_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('source_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='book.book')),
            ],
        ),
    ]
