# Generated by Django 4.2.6 on 2023-10-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('desc', models.TextField(verbose_name='description')),
                ('format', models.CharField(max_length=100, verbose_name='format')),
                ('isbn', models.IntegerField(verbose_name='isbn')),
                ('pages', models.IntegerField(verbose_name='pages')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('genre', models.IntegerField(verbose_name='genre')),
                ('image', models.TextField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
