# Generated by Django 4.2.6 on 2023-10-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('num_of_pages', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('counts_of_review', models.IntegerField(blank=True, null=True)),
                ('rating_dist_total', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_dist1', models.IntegerField(blank=True, null=True)),
                ('rating_dist2', models.IntegerField(blank=True, null=True)),
                ('rating_dist3', models.IntegerField(blank=True, null=True)),
                ('rating_dist4', models.IntegerField(blank=True, null=True)),
                ('rating_dist5', models.IntegerField(blank=True, null=True)),
                ('indices', models.CharField(blank=True, max_length=700, null=True)),
                ('distance', models.CharField(blank=True, max_length=700, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('small_image_url', models.URLField(blank=True, null=True)),
                ('publish_day', models.IntegerField(blank=True, null=True)),
                ('publish_month', models.IntegerField(blank=True, null=True)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('status',models.CharField(choices=[('Available', 'a'), ('Borrowed', 'b')], default='Available', max_length=10)),
            ],
        ),
    ]
