# Generated by Django 4.1.7 on 2023-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231024_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'a'), ('Borrowed', 'b')], default='Available', max_length=10),
        ),
    ]
