# Generated by Django 4.2.5 on 2023-10-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_status'),
    ]

    operations = [
    ]
